version: '2'
services:
  web:
    image: node:8
    volumes: 
      - ./web:/app/
    ports: 
      - "$WEB_PORT:$WEB_PORT"
    environment: 
      - PORT=$WEB_PORT
    working_dir: /app/
    links:
      - db
    tty: true
    command: 
      npm start
    depends_on: 
      - db
  db:
    image: mongo
    tty: true