version: '2'
services:
  api:
    image: node:8
    volumes: 
      - ./api:/app/
    ports: 
      - "$API_PORT:$API_PORT"
    environment: 
      - PORT=$API_PORT
    working_dir: /app/
    links:
      - db
    tty: true
    command: 
      npm start
    depends_on: 
      - db
  client:
    image: node:8
    volumes:
      - ./client:/app/
    ports: 
      - "$CLIENT_PORT:$CLIENT_PORT"
    environment: 
      - PORT=$CLIENT_PORT
    working_dir: /app/
    links:
      - api
    command: 
      npm start
    depends_on: 
      - api
  db:
    image: mongo
    tty: true